
package org.informatika.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AssetLifecycleManagement", targetNamespace = "http://service.informatika.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AssetLifecycleManagement {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "close", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.CloseResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/closeRequest", output = "http://service.informatika.org/AssetLifecycleManagement/closeResponse")
    public void close();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.RegisterAset")
    @ResponseWrapper(localName = "registerAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.RegisterAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/registerAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/registerAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/registerAset/Fault/SQLException")
    })
    public Response registerAset(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        AssetCondition arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertJadwalMaintenance", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertJadwalMaintenance")
    @ResponseWrapper(localName = "insertJadwalMaintenanceResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertJadwalMaintenanceResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/insertJadwalMaintenanceRequest", output = "http://service.informatika.org/AssetLifecycleManagement/insertJadwalMaintenanceResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/insertJadwalMaintenance/Fault/SQLException")
    })
    public Response insertJadwalMaintenance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        MaintenanceCycleTimeUnit arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerVendor", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.RegisterVendor")
    @ResponseWrapper(localName = "registerVendorResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.RegisterVendorResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/registerVendorRequest", output = "http://service.informatika.org/AssetLifecycleManagement/registerVendorResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/registerVendor/Fault/SQLException")
    })
    public Response registerVendor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.DeleteAset")
    @ResponseWrapper(localName = "deleteAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.DeleteAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/deleteAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/deleteAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/deleteAset/Fault/SQLException")
    })
    public Response deleteAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNamaAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetNamaAset")
    @ResponseWrapper(localName = "setNamaAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetNamaAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setNamaAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setNamaAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setNamaAset/Fault/SQLException")
    })
    public Response setNamaAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPemilikAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetPemilikAset")
    @ResponseWrapper(localName = "setPemilikAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetPemilikAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setPemilikAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setPemilikAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setPemilikAset/Fault/SQLException")
    })
    public Response setPemilikAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setKondisiAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetKondisiAset")
    @ResponseWrapper(localName = "setKondisiAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetKondisiAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setKondisiAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setKondisiAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setKondisiAset/Fault/SQLException")
    })
    public Response setKondisiAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AssetCondition arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setJenisAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetJenisAset")
    @ResponseWrapper(localName = "setJenisAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SetJenisAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setJenisAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setJenisAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setJenisAset/Fault/SQLException")
    })
    public Response setJenisAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertKebutuhanMaintenance", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertKebutuhanMaintenance")
    @ResponseWrapper(localName = "insertKebutuhanMaintenanceResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertKebutuhanMaintenanceResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/insertKebutuhanMaintenanceRequest", output = "http://service.informatika.org/AssetLifecycleManagement/insertKebutuhanMaintenanceResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/insertKebutuhanMaintenance/Fault/SQLException")
    })
    public Response insertKebutuhanMaintenance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Integer> arg2)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertFasilitasAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertFasilitasAset")
    @ResponseWrapper(localName = "insertFasilitasAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.InsertFasilitasAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/insertFasilitasAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/insertFasilitasAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/insertFasilitasAset/Fault/SQLException")
    })
    public Response insertFasilitasAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.informatika.client.Asset
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAset")
    @ResponseWrapper(localName = "getAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/getAset/Fault/SQLException")
    })
    public Asset getAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.informatika.client.Asset>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsetByKategori", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByKategori")
    @ResponseWrapper(localName = "getAsetByKategoriResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByKategoriResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAsetByKategoriRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAsetByKategoriResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/getAsetByKategori/Fault/SQLException")
    })
    public List<Asset> getAsetByKategori(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.informatika.client.Asset
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsetByNama", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByNama")
    @ResponseWrapper(localName = "getAsetByNamaResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByNamaResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAsetByNamaRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAsetByNamaResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/getAsetByNama/Fault/SQLException")
    })
    public Asset getAsetByNama(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.informatika.client.Asset>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsetByJenis", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByJenis")
    @ResponseWrapper(localName = "getAsetByJenisResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetAsetByJenisResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAsetByJenisRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAsetByJenisResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/getAsetByJenis/Fault/SQLException")
    })
    public List<Asset> getAsetByJenis(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.informatika.client.Asset>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFasilitasAset", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetFasilitasAset")
    @ResponseWrapper(localName = "getFasilitasAsetResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.GetFasilitasAsetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getFasilitasAsetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getFasilitasAsetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/getFasilitasAset/Fault/SQLException")
    })
    public List<Asset> getFasilitasAset(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.informatika.client.Response
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyMaintenanceToVendor", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.NotifyMaintenanceToVendor")
    @ResponseWrapper(localName = "notifyMaintenanceToVendorResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.NotifyMaintenanceToVendorResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/notifyMaintenanceToVendorRequest", output = "http://service.informatika.org/AssetLifecycleManagement/notifyMaintenanceToVendorResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/notifyMaintenanceToVendor/Fault/SQLException")
    })
    public Response notifyMaintenanceToVendor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws SQLException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://service.informatika.org/", className = "org.informatika.client.SayHelloWorldResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/sayHelloWorldRequest", output = "http://service.informatika.org/AssetLifecycleManagement/sayHelloWorldResponse")
    public String sayHelloWorld();

}
