
package asset;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AssetLifecycleManagement", targetNamespace = "http://service.informatika.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AssetLifecycleManagement {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "close", targetNamespace = "http://service.informatika.org/", className = "asset.Close")
    @ResponseWrapper(localName = "closeResponse", targetNamespace = "http://service.informatika.org/", className = "asset.CloseResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/closeRequest", output = "http://service.informatika.org/AssetLifecycleManagement/closeResponse")
    public void close();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerAsset", targetNamespace = "http://service.informatika.org/", className = "asset.RegisterAsset")
    @ResponseWrapper(localName = "registerAssetResponse", targetNamespace = "http://service.informatika.org/", className = "asset.RegisterAssetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/registerAssetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/registerAssetResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/registerAsset/Fault/SQLException")
    })
    public String registerAsset(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            AssetCondition arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
            int arg4,
            @WebParam(name = "arg5", targetNamespace = "")
            String arg5)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertMaintenanceSchedule", targetNamespace = "http://service.informatika.org/", className = "asset.InsertMaintenanceSchedule")
    @ResponseWrapper(localName = "insertMaintenanceScheduleResponse", targetNamespace = "http://service.informatika.org/", className = "asset.InsertMaintenanceScheduleResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/insertMaintenanceScheduleRequest", output = "http://service.informatika.org/AssetLifecycleManagement/insertMaintenanceScheduleResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/insertMaintenanceSchedule/Fault/SQLException")
    })
    public String insertMaintenanceSchedule(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            int arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            String arg3)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerVendor", targetNamespace = "http://service.informatika.org/", className = "asset.RegisterVendor")
    @ResponseWrapper(localName = "registerVendorResponse", targetNamespace = "http://service.informatika.org/", className = "asset.RegisterVendorResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/registerVendorRequest", output = "http://service.informatika.org/AssetLifecycleManagement/registerVendorResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/registerVendor/Fault/SQLException")
    })
    public String registerVendor(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            String arg3)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAsset", targetNamespace = "http://service.informatika.org/", className = "asset.DeleteAsset")
    @ResponseWrapper(localName = "deleteAssetResponse", targetNamespace = "http://service.informatika.org/", className = "asset.DeleteAssetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/deleteAssetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/deleteAssetResponse")
    public String deleteAsset(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAssetOwner", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetOwner")
    @ResponseWrapper(localName = "setAssetOwnerResponse", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetOwnerResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setAssetOwnerRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setAssetOwnerResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setAssetOwner/Fault/SQLException")
    })
    public String setAssetOwner(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAssetCondition", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetCondition")
    @ResponseWrapper(localName = "setAssetConditionResponse", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetConditionResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setAssetConditionRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setAssetConditionResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setAssetCondition/Fault/SQLException")
    })
    public String setAssetCondition(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            AssetCondition arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAssetJenis", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetJenis")
    @ResponseWrapper(localName = "setAssetJenisResponse", targetNamespace = "http://service.informatika.org/", className = "asset.SetAssetJenisResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/setAssetJenisRequest", output = "http://service.informatika.org/AssetLifecycleManagement/setAssetJenisResponse", fault = {
        @FaultAction(className = SQLException_Exception.class, value = "http://service.informatika.org/AssetLifecycleManagement/setAssetJenis/Fault/SQLException")
    })
    public String setAssetJenis(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssetbyKategori", targetNamespace = "http://service.informatika.org/", className = "asset.GetAssetbyKategori")
    @ResponseWrapper(localName = "getAssetbyKategoriResponse", targetNamespace = "http://service.informatika.org/", className = "asset.GetAssetbyKategoriResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAssetbyKategoriRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAssetbyKategoriResponse")
    public String getAssetbyKategori(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAsset", targetNamespace = "http://service.informatika.org/", className = "asset.GetAsset")
    @ResponseWrapper(localName = "getAssetResponse", targetNamespace = "http://service.informatika.org/", className = "asset.GetAssetResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/getAssetRequest", output = "http://service.informatika.org/AssetLifecycleManagement/getAssetResponse")
    public String getAsset(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notifyAssetMaintenance", targetNamespace = "http://service.informatika.org/", className = "asset.NotifyAssetMaintenance")
    @ResponseWrapper(localName = "notifyAssetMaintenanceResponse", targetNamespace = "http://service.informatika.org/", className = "asset.NotifyAssetMaintenanceResponse")
    @Action(input = "http://service.informatika.org/AssetLifecycleManagement/notifyAssetMaintenanceRequest", output = "http://service.informatika.org/AssetLifecycleManagement/notifyAssetMaintenanceResponse")
    public String notifyAssetMaintenance(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
